[".config/alacritty/themes"]
refreshPeriod = "0"
type = "git-repo"
url = "https://github.com/alacritty/alacritty-theme.git"

[".config/nvim"]
refreshPeriod = "0"
type = "git-repo"
url = "https://github.com/NvChad/NvChad.git"
