UI:
  Scrollbar: true
  Zoom: false
  Theme: default
  Language: zh
  TimeZone: ""
Search:
  BatchSize: 0
Maps:
  Animate: 0
  Style: ""
Features:
  Account: false
  Albums: true
  Archive: true
  Delete: false
  Download: true
  Edit: true
  Estimates: false
  Favorites: true
  Files: false
  Folders: true
  Import: true
  Labels: false
  Library: false
  Logs: false
  Moments: false
  People: false
  Places: true
  Private: false
  Ratings: true
  Reactions: true
  Review: true
  Search: true
  Services: true
  Settings: true
  Share: true
  Upload: true
  Videos: true
Import:
  Path: /
  Move: false
Index:
  Path: videos
  Convert: true
  Rescan: false
  SkipArchived: false
Stack:
  UUID: true
  Meta: true
  Name: true
Share:
  Title: ""
Download:
  Name: file
  Disabled: false
  Originals: true
  MediaRaw: false
  MediaSidecar: true
Templates:
  Default: index.gohtml
