version: '3.1'

services:
  # db:
  #   image: mysql
  #   # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
  #   # (this is just an example, not intended to be a production configuration)
  #   # command: --default-authentication-plugin=mysql_native_password
  #   restart: unless-stopped
  #   ports:
  #     - '3307:3306'
  #   # network_mode: host
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  #   volumes:
  #     - ./data:/var/lib/mysql

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    # ports:
    #   - '3307:3306'
    network_mode: host
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}

  # adminer:
  # image: adminer
  # restart: always
  # ports:
  # - 8086:8080
