version: '3.8'

# echo "https://aria.home.lubui.com:8443/ui/#!/settings/rpc/set/wss/aria.home.lubui.com/8443/jsonrpc/$(echo -n "xxx" | base64)"

services:
  aria2-server:
    container_name: aria2-pro
    image: p3terx/aria2-pro
    environment:
      PUID: 65534
      PGID: 65534
      UMASK_SET: 022
      RPC_SECRET:
      RPC_PORT: 6800
      LISTEN_PORT: 6888
      DISK_CACHE: 64M
      IPV6_MODE: false
      UPDATE_TRACKERS: true
      CUSTOM_TRACKER_URL:
      TZ: Asia/Shanghai
    volumes:
      - ${PWD}/aria2-config:/config
      - ~/Downloads:/downloads
    # ports:
    #   - 6800:6800
    #   - 6888:6888
    #   - 6888:6888/udp
    network_mode: host
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 1m
    labels:
      - com.centurylinklabs.watchtower.enable=true

  aria_ng:
    container_name: aria_ng
    build: ./aria_ng
    network_mode: host
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: aria.home.lubui.com
      VIRTUAL_PORT: 6880
    logging:
      driver: json-file
      options:
        max-size: 1m
