version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000 # should be owner of volumes
    # ports:
      # - "4533:4533"
    restart: unless-stopped
    network_mode: host
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 240h
      ND_BASEURL: ""
      ND_SPOTIFY_ID: 
      ND_SPOTIFY_SECRET: 
      ND_MUSICFOLDER: /music
      ND_DEFAULTLANGUAGE: zh
      ND_LASTFM_ENABLED: true
      ND_LASTFM_APIKEY: 
      ND_LASTFM_SECRET: 
      ND_LASTFM_LANGUAGE: zh
    volumes:
      - "./data:/data"
      - "./music:/music"
    labels:
      - homepage.group=媒体
      - homepage.name=Navidrome
      - homepage.icon=navidrome.png
      - homepage.href=http://home.lubui.com:4533/
      - homepage.description=音乐库
      - com.centurylinklabs.watchtower.enable=true
