version: "3.7"
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    environment:
      TZ: Asia/Shanghai
      PORT: 13378
    # ports:
    #   - 13378:80
    network_mode: host
    volumes:
      - ./audiobooks:/audiobooks
      - ./podcasts:/podcasts
      - ./config:/config
      - ./metadata:/metadata
    restart: unless-stopped
    labels:
      - homepage.group=媒体
      - homepage.name=AudioBookShelf
      - homepage.icon=audiobookshelf.png
      - homepage.href=http://home.lubui.com:13378/
      - homepage.description=有声图书
      - com.centurylinklabs.watchtower.enable=true
    
