services:
  chatgpt:
    container_name: chatgpt-next-web
    image: yidadaa/chatgpt-next-web
    environment:
      TZ: Asia/Shanghai
      OPENAI_API_KEY:
      CODE:
      PORT: 3010
      VIRTUAL_HOST: gpt.home.lubui.com
      VIRTUAL_PORT: 3010
    network_mode: host
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
