version: '3.3'

services:
  clash:
    # image: dreamacro/clash-premium
    build: .
    container_name: clash
    environment:
      TZ: Asia/Shanghai
      VIRTUAL_HOST: clash.home.lubui.com
      VIRTUAL_PORT: 9090
    volumes:
      - ./config:/root/.config/clash
      # - ./ui:/ui # dashboard volume
    network_mode: host
    # ports:
    #   - "7892:7892"
    #   - "9090:9090"
    #   - "10809:10809"
    # TUN
    dns:
      - 223.5.5.5
      - 223.6.6.6
    cap_add:
      - NET_ADMIN
    # devices:
    #   - /dev/net/tun
    # privileged: true
    restart: unless-stopped
