version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    # ports:
    #   - 3000:3000
    network_mode: host
    environment:
      TZ: Asia/Shanghai
      PORT: 3015
      VIRTUAL_HOST: home.lubui.com
      VIRTUAL_PORT: 3015
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "home.lubui.com:192.168.1.7"
    restart: unless-stopped
    # environment:
      # - LOG_LEVEL=debug
    labels:
      - com.centurylinklabs.watchtower.enable=true
