version: "3.8"

services:
  ddns:
    container_name: ddns-go
    image: jeessy/ddns-go
    volumes:
      - ./config:/root
    network_mode: host
    # ports:
    #   - 9876:9876
    environment:
      TZ: Asia/Shanghai
      VIRTUAL_HOST: ddns.home.lubui.com
      VIRTUAL_PORT: 9876
      PATH_NEED_SSO: /
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
