services:
  chatgpt-on-wechat:
    image: zhayujie/chatgpt-on-wechat
    container_name: chatgpt-on-wechat
    environment:
      OPEN_AI_API_KEY:
      MODEL: 'gpt-3.5-turbo'
      PROXY: ''
      SINGLE_CHAT_PREFIX: '["bot", "@bot", "AI", "机器人，"]'
      SINGLE_CHAT_REPLY_PREFIX: '"[bot] "'
      GROUP_CHAT_PREFIX: '["@bot", "AI", "机器人，"]'
      GROUP_NAME_WHITE_LIST: '["小分队微信版", "人类高质量幼崽早期圈养观察群", "幸福一家人"]'
      IMAGE_CREATE_PREFIX: '["画", "看", "找"]'
      CONVERSATION_MAX_TOKENS: 1000
      SPEECH_RECOGNITION: 'False'
      CHARACTER_DESC: '你是ChatGPT, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。'
      EXPIRES_IN_SECONDS: 3600
      USE_LINKAI: 'False'
      LINKAI_API_KEY: ''
      LINKAI_APP_CODE: ''
      HOT_RELOAD: 'True'
    # network_mode: host
    restart: unless-stopped
    # labels:
    #   - homepage.group=媒体
    #   - homepage.name=ChatGPT
    #   - homepage.icon=chatgpt.png
    #   - homepage.href=http://home.lubui.com:3010/
    #   - homepage.description=智能语言模型
    #   - com.centurylinklabs.watchtower.enable=true
