services:
  nginx:
    image: nginx:latest
    container_name: nginx
    environment:
      TZ: Asia/Shanghai
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ~/.lego/certificates/:/etc/nginx/certs
    logging:
      driver: json-file
      options:
        max-size: 1m

  dockergen:
    image: nginxproxy/docker-gen
    container_name: docker-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl
      /etc/nginx/conf.d/default.conf
    environment:
      TZ: Asia/Shanghai
      HTTPS_PORT: 8443
      HTTP_PORT: 1080
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
      - ~/.lego/certificates/:/etc/nginx/certs

  # whoami:
  #   image: traefik/whoami
  #   network_mode: host
  #   environment:
  #     - VIRTUAL_HOST=a.home.lubui.com
  #     - VIRTUAL_PORT=80
