version: "2.4"

services:

  freshrss:
    image: freshrss/freshrss:alpine
    # Optional build section if you want to build the image locally:
    # build:
    #   # Pick #latest (stable release) or #edge (rolling release) or a specific release like #1.21.0
    #   context: https://github.com/FreshRSS/FreshRSS.git#latest
    #   dockerfile: Docker/Dockerfile-Alpine
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - ./data:/var/www/FreshRSS/data
      - ./extensions:/var/www/FreshRSS/extensions
    environment:
      TZ: Asia/Shanghai
      CRON_MIN: '3,33'
      LISTEN: 0.0.0.0:3011
      FRESHRSS_INSTALL: |-
        --api_enabled
        --base_url http://home.lubui.com:3011
        --db-base freshrss
        --db-host 127.0.0.1
        --db-password ${DB_PASSWORD}
        --db-type mysql
        --db-user root
        --default_user urie
        --language zh
      FRESHRSS_USER: |-
        --api_password ${API_PASSWORD}
        --email lubui.com@gmail.com
        --language zh
        --password ${PASSWORD}
        --user urie
    network_mode: host
    labels:
      - homepage.group=工具
      - homepage.name=FreshRSS
      - homepage.icon=freshrss.png
      - homepage.href=http://home.lubui.com:3011/
      - homepage.description=RSS聚合器
      - com.centurylinklabs.watchtower.enable=true
